// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbtu64dT8jascv1XqV9PFMIBrOrmUbGA0',
    appId: '1:520640514056:web:df54c2ae1c06bb3682a9bd',
    messagingSenderId: '520640514056',
    projectId: 'cw-7-197c1',
    authDomain: 'cw-7-197c1.firebaseapp.com',
    storageBucket: 'cw-7-197c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBX1MnzWZRxPElahAEJ7XhvyZomy1X3bE',
    appId: '1:520640514056:android:a4d40841bb50fa6682a9bd',
    messagingSenderId: '520640514056',
    projectId: 'cw-7-197c1',
    storageBucket: 'cw-7-197c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWvExJ6zG7cpsrfFkCy6k7pk5d3ejnvc4',
    appId: '1:520640514056:ios:ea54d64e82c2e84682a9bd',
    messagingSenderId: '520640514056',
    projectId: 'cw-7-197c1',
    storageBucket: 'cw-7-197c1.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWvExJ6zG7cpsrfFkCy6k7pk5d3ejnvc4',
    appId: '1:520640514056:ios:ea54d64e82c2e84682a9bd',
    messagingSenderId: '520640514056',
    projectId: 'cw-7-197c1',
    storageBucket: 'cw-7-197c1.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbtu64dT8jascv1XqV9PFMIBrOrmUbGA0',
    appId: '1:520640514056:web:91681f8a1015b15d82a9bd',
    messagingSenderId: '520640514056',
    projectId: 'cw-7-197c1',
    authDomain: 'cw-7-197c1.firebaseapp.com',
    storageBucket: 'cw-7-197c1.firebasestorage.app',
  );
}
